version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    groups:
      spring-boot:
        patterns:
          - "org.springframework.boot:*"
      jackson:
        patterns:
          - "com.fasterxml.jackson.*"
      log4:
        patterns:
          - "org.apache.logging.log4j:*"
      spring-framework:
        patterns:
          - "org.springframework:*"
      bouncycastle:
        patterns:
          - "org.bouncycastle:*"

  - package-ecosystem: "npm"
    directory: "/kmc-sa-mgmt/kmc-sa-gui/src/main/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
