# Sample DCS SDLS Test Application Properties File
# See the DCS SIS for descriptions of each supported property.

# SADB Configuration Parameters
cryptolib.sadb.type=mariadb
# cryptolib.sadb.mariadb.fqdn=crypto123.example.com
cryptolib.sadb.mariadb.fqdn=
cryptolib.sadb.mariadb.port=3306
cryptolib.sadb.mariadb.username=testuser2
# Password not necessary when using mTLS
cryptolib.sadb.mariadb.password=
cryptolib.sadb.mariadb.tls.cacert=/etc/pki/tls/certs/ammos-ca-bundle.crt
cryptolib.sadb.mariadb.tls.verifyserver=true
cryptolib.sadb.mariadb.mtls.clientcert=/opt/ammos/kmc/test/etc/ammos-client-cert.pem
cryptolib.sadb.mariadb.mtls.clientkey=/opt/ammos/kmc/test/etc/ammos-client-key.pem
cryptolib.sadb.mariadb.require_secure_transport=true

# Crypto Configuration Parameters
cryptolib.crypto.type=kmccryptoservice
cryptolib.crypto.kmccryptoservice.protocol=https
# cryptolib.crypto.kmccryptoservice.fqdn=crypto123.example.com
cryptolib.crypto.kmccryptoservice.fqdn=
cryptolib.crypto.kmccryptoservice.port=8443
cryptolib.crypto.kmccryptoservice.app=crypto-service
cryptolib.crypto.kmccryptoservice.mtls.clientcert=/opt/ammos/kmc/test/etc/ammos-client-cert.pem
cryptolib.crypto.kmccryptoservice.mtls.clientcertformat=PEM
cryptolib.crypto.kmccryptoservice.mtls.clientkey=/opt/ammos/kmc/test/etc/ammos-client-key.pem
cryptolib.crypto.kmccryptoservice.cacert=/etc/pki/tls/certs/ammos-ca-bundle.crt
cryptolib.crypto.kmccryptoservice.verifyserver=true

# CryptoLib Global Behavioral Properties for TC
cryptolib.tc.create_ecf=true
cryptolib.tc.vcid_bitmask=0x3f
cryptolib.tc.ignore_antireplay=true
cryptolib.tc.ignore_sa_state=true
cryptolib.tc.process_pdus=false
cryptolib.tc.check_fecf=false
cryptolib.tc.on_rollover_increment_nontransmitted_counter=true

# Managed Parameters for TC
# cryptolib.tc.<scid>.<vcid>.<tfvn>.<property>
cryptolib.tc.44.0.0.has_segmentation_header=false
cryptolib.tc.44.0.0.has_pus_header=false
cryptolib.tc.44.0.0.has_ecf=true
cryptolib.tc.44.0.0.max_frame_length=128
cryptolib.tc.44.1.0.has_segmentation_header=false
cryptolib.tc.44.1.0.has_pus_header=false
cryptolib.tc.44.1.0.has_ecf=true
cryptolib.tc.44.1.0.max_frame_length=128
cryptolib.tc.44.2.0.has_segmentation_header=false
cryptolib.tc.44.2.0.has_pus_header=false
cryptolib.tc.44.2.0.has_ecf=true
cryptolib.tc.44.2.0.max_frame_length=128
cryptolib.tc.44.3.0.has_segmentation_header=false
cryptolib.tc.44.3.0.has_pus_header=false
cryptolib.tc.44.3.0.has_ecf=true
cryptolib.tc.44.3.0.max_frame_length=128

# CryptoLib Global Behavioral Properties for AOS
cryptolib.aos.vcid_bitmask=0x3f
cryptolib.aos.create_ecf=true
cryptolib.aos.check_fecf=false
cryptolib.aos.ignore_antireplay=true
cryptolib.aos.on_rollover_increment_nontransmitted_counter=true

# Managed Parameters for AOS
# cryptolib.aos.<scid>.<vcid>.<tfvn>.<property>
cryptolib.aos.44.0.1.has_ecf=true
cryptolib.aos.44.0.1.has_fhec=false
cryptolib.aos.44.0.1.has_iz=false
cryptolib.aos.44.0.1.iz_len=0
cryptolib.aos.44.0.1.has_ocf=false
cryptolib.aos.44.0.1.max_frame_length=128
cryptolib.aos.44.1.1.has_ecf=true
cryptolib.aos.44.1.1.max_frame_length=128
cryptolib.aos.45.0.1.has_ecf=true
cryptolib.aos.45.0.1.max_frame_length=128

# CryptoLib Global Behavioral Properties for TM
cryptolib.tm.vcid_bitmask=0x3f
cryptolib.tm.create_ecf=true
cryptolib.tm.check_fecf=false
cryptolib.tm.ignore_antireplay=true
cryptolib.tm.on_rollover_increment_nontransmitted_counter=true

# Managed Parameters for TM
# cryptolib.tm.<scid>.<vcid>.<tfvn>.<property>
cryptolib.tm.44.0.0.has_ecf=true
cryptolib.tm.44.0.0.max_frame_length=128
cryptolib.tm.44.0.0.has_ocf=false
cryptolib.tm.44.1.0.has_ecf=true
cryptolib.tm.44.1.0.has_ocf=false
cryptolib.tm.44.1.0.max_frame_length=128
cryptolib.tm.45.0.0.has_ecf=true
cryptolib.tm.45.0.0.has_ocf=false
cryptolib.tm.45.0.0.max_frame_length=128
