version: '3.5'

secrets:
  tls_host_cert:
    external: true
  tls_host_key:
    external: true
  tls_mtls_truststore:
    external: true
  tls_mtls_truststore_pass:
    external: true
  tls_ca_bundle:
    external: true

services:
  cryptosvc:
    image: kmc-sdls-service:4.0.0
    ports:
      - "8447:8447"
    restart: always
    secrets:
      - tls_host_cert
      - tls_host_key
      - tls_mtls_truststore
      - tls_mtls_truststore_pass
      - tls_ca_bundle
    environment:
      SADB_FQDN: "sadb.example.com"
